"""
Generate extended simulation parameters for all 40 scenario instances.
Maps to the 12 scenario families in the catalog.
"""
import csv
import json
import os

OUTPUT_DIR = "/mnt/user-data/outputs/synthetic_data"

# ============================================================
# ALL 40 SCENARIO DEFINITIONS
# ============================================================

SCENARIOS = [
    # -------------------------------------------------------
    # PRIORITY 1: Core Forward Simulations (8)
    # -------------------------------------------------------
    {
        "scenario_id": "SC-1.1",
        "scenario_family": "technology_injection",
        "scenario_name": "Copilot → Claims Processing",
        "direction": "forward",
        "target_scope": "Claims Processing",
        "target_functions": "Claims",
        "target_roles": "",
        "tools": "Microsoft Copilot",
        "deployment_months": "1",
        "adoption_phases": "adoption",
        "alpha_adopt": 0.6, "alpha_expand": 0.0, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "moderate_reduction",
        "redistribution_mode": "absorb_adjacent",
        "readiness_threshold": 0,
        "budget_total": 500000,
        "max_risk_level": "medium",
        "time_horizon_months": 36,
        "objective": "maximize_savings",
        "events": "[]",
        "notes": "Basic cascade validation — single tool, single function",
    },
    {
        "scenario_id": "SC-1.2",
        "scenario_family": "technology_injection",
        "scenario_name": "Copilot → All Functions",
        "direction": "forward",
        "target_scope": "ALL",
        "target_functions": "Claims,Technology,Finance,People",
        "target_roles": "",
        "tools": "Microsoft Copilot",
        "deployment_months": "1",
        "adoption_phases": "adoption",
        "alpha_adopt": 0.6, "alpha_expand": 0.0, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "moderate_reduction",
        "redistribution_mode": "absorb_adjacent",
        "readiness_threshold": 0,
        "budget_total": 2000000,
        "max_risk_level": "medium",
        "time_horizon_months": 36,
        "objective": "maximize_savings",
        "events": "[]",
        "notes": "Same tool, all functions — proves human system variation",
    },
    {
        "scenario_id": "SC-1.5",
        "scenario_family": "technology_injection",
        "scenario_name": "Adoption Gap Only (Free Money)",
        "direction": "forward",
        "target_scope": "ALL",
        "target_functions": "Claims,Technology,Finance,People",
        "target_roles": "",
        "tools": "ALL_DEPLOYED",
        "deployment_months": "1",
        "adoption_phases": "adoption",
        "alpha_adopt": 0.5, "alpha_expand": 0.0, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "natural_attrition",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 0,
        "budget_total": 200000,
        "max_risk_level": "low",
        "time_horizon_months": 36,
        "objective": "maximize_savings",
        "events": "[]",
        "notes": "Close adoption gap on already-deployed tools — near-zero cost, immediate value",
    },
    {
        "scenario_id": "SC-5.2",
        "scenario_family": "output_target",
        "scenario_name": "Maintain Output, -20% Claims HC",
        "direction": "inverse",
        "target_scope": "Claims",
        "target_functions": "Claims",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "",
        "adoption_phases": "adoption,expansion",
        "alpha_adopt": 0.6, "alpha_expand": 0.3, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "moderate_reduction",
        "redistribution_mode": "automate_first",
        "readiness_threshold": 50,
        "budget_total": 3000000,
        "max_risk_level": "medium",
        "time_horizon_months": 24,
        "objective": "maintain_output",
        "events": "[]",
        "target_metric": "headcount_reduction_pct",
        "target_value": 20,
        "output_constraint": "maintain_current_volume",
        "notes": "Core business case — same work, fewer people",
    },
    {
        "scenario_id": "SC-7.1",
        "scenario_family": "function_transformation",
        "scenario_name": "Claims Phased Transformation",
        "direction": "forward",
        "target_scope": "Claims",
        "target_functions": "Claims",
        "target_roles": "",
        "tools": "UiPath RPA,Custom Claims AI,Microsoft Copilot",
        "deployment_months": "1,7,13",
        "adoption_phases": "adoption,expansion,extension",
        "alpha_adopt": 0.7, "alpha_expand": 0.4, "alpha_extend": 0.2,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "moderate_reduction",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 45,
        "budget_total": 4000000,
        "max_risk_level": "high",
        "time_horizon_months": 36,
        "objective": "maximize_savings",
        "events": "[]",
        "notes": "Full function transformation — 3 phases with staggered tools",
    },
    {
        "scenario_id": "SC-10.6",
        "scenario_family": "baseline",
        "scenario_name": "Do Nothing (Cost of Inaction)",
        "direction": "forward",
        "target_scope": "ALL",
        "target_functions": "Claims,Technology,Finance,People",
        "target_roles": "",
        "tools": "",
        "deployment_months": "",
        "adoption_phases": "",
        "alpha_adopt": 0.0, "alpha_expand": 0.0, "alpha_extend": 0.0,
        "s_curve_k": 0.0, "s_curve_midpoint": 0,
        "hc_policy": "no_change",
        "redistribution_mode": "none",
        "readiness_threshold": 0,
        "budget_total": 0,
        "max_risk_level": "low",
        "time_horizon_months": 36,
        "objective": "baseline",
        "events": "[]",
        "natural_attrition_annual_pct": 8,
        "salary_inflation_annual_pct": 3,
        "competitor_automation_growth_pct": 10,
        "notes": "Baseline — growing cost, increasing competitive gap",
    },
    {
        "scenario_id": "SC-6.1",
        "scenario_family": "role_transformation",
        "scenario_name": "Redesign Claims Adjuster",
        "direction": "forward",
        "target_scope": "CL-002",
        "target_functions": "Claims",
        "target_roles": "CL-002",
        "tools": "Microsoft Copilot,Custom Claims AI",
        "deployment_months": "1,1",
        "adoption_phases": "adoption",
        "alpha_adopt": 0.6, "alpha_expand": 0.0, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "role_redesign",
        "redistribution_mode": "absorb_adjacent",
        "readiness_threshold": 0,
        "budget_total": 300000,
        "max_risk_level": "medium",
        "time_horizon_months": 24,
        "objective": "role_redesign",
        "events": "[]",
        "notes": "Single role deep dive — future JD, skill shift, adjacency impact",
    },
    {
        "scenario_id": "SC-8.1",
        "scenario_family": "skill_intervention",
        "scenario_name": "Claims AI Academy",
        "direction": "forward",
        "target_scope": "Claims",
        "target_functions": "Claims",
        "target_roles": "",
        "tools": "",
        "deployment_months": "",
        "adoption_phases": "",
        "alpha_adopt": 0.0, "alpha_expand": 0.0, "alpha_extend": 0.0,
        "s_curve_k": 0.0, "s_curve_midpoint": 0,
        "hc_policy": "no_change",
        "redistribution_mode": "none",
        "readiness_threshold": 0,
        "budget_total": 500000,
        "max_risk_level": "low",
        "time_horizon_months": 24,
        "objective": "build_capability",
        "events": "[]",
        "reskilling_target_hc": 450,
        "reskilling_duration_months": 6,
        "proficiency_lift": 25,
        "notes": "Reskilling only — no tech deployment. Proves R2 proficiency flywheel.",
    },

    # -------------------------------------------------------
    # PRIORITY 2: Inverse & Optimization (8)
    # -------------------------------------------------------
    {
        "scenario_id": "SC-2.1",
        "scenario_family": "headcount_target",
        "scenario_name": "Reduce 15% Org-Wide",
        "direction": "inverse",
        "target_scope": "ALL",
        "target_functions": "Claims,Technology,Finance,People",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "",
        "adoption_phases": "adoption,expansion",
        "alpha_adopt": 0.6, "alpha_expand": 0.3, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "managed_reduction",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 50,
        "budget_total": 5000000,
        "max_risk_level": "medium",
        "time_horizon_months": 24,
        "objective": "achieve_target",
        "events": "[]",
        "target_metric": "headcount_reduction_pct",
        "target_value": 15,
        "notes": "Inverse: what tools, budget, timeline to reach 15% HC reduction?",
    },
    {
        "scenario_id": "SC-2.2",
        "scenario_family": "headcount_target",
        "scenario_name": "Differentiated Function Targets",
        "direction": "inverse",
        "target_scope": "MULTI",
        "target_functions": "Claims,Technology,Finance,People",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "",
        "adoption_phases": "adoption,expansion",
        "alpha_adopt": 0.6, "alpha_expand": 0.3, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "managed_reduction",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 0,
        "budget_total": 6000000,
        "max_risk_level": "high",
        "time_horizon_months": 24,
        "objective": "achieve_target",
        "events": "[]",
        "target_metric": "headcount_by_function",
        "target_value_json": '{"Claims": -25, "Technology": 0, "Finance": -10, "People": -15}',
        "notes": "Claims -25%, Tech flat, Finance -10%, People -15%. Feasibility per function.",
    },
    {
        "scenario_id": "SC-4.1",
        "scenario_family": "automation_target",
        "scenario_name": "Reach 35% Automation",
        "direction": "inverse",
        "target_scope": "ALL",
        "target_functions": "Claims,Technology,Finance,People",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "",
        "adoption_phases": "adoption,expansion,extension",
        "alpha_adopt": 0.7, "alpha_expand": 0.4, "alpha_extend": 0.2,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "moderate_reduction",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 50,
        "budget_total": 8000000,
        "max_risk_level": "high",
        "time_horizon_months": 36,
        "objective": "achieve_target",
        "events": "[]",
        "target_metric": "automation_pct",
        "target_value": 35,
        "notes": "Inverse: roadmap to 35% automation from current ~12% realized",
    },
    {
        "scenario_id": "SC-3.1",
        "scenario_family": "budget_constraint",
        "scenario_name": "$2M Optimized Allocation",
        "direction": "optimization",
        "target_scope": "ALL",
        "target_functions": "Claims,Technology,Finance,People",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "",
        "adoption_phases": "adoption,expansion",
        "alpha_adopt": 0.6, "alpha_expand": 0.3, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "moderate_reduction",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 40,
        "budget_total": 2000000,
        "max_risk_level": "medium",
        "time_horizon_months": 24,
        "objective": "maximize_savings",
        "events": "[]",
        "notes": "$2M budget — find best allocation across tools, functions, phases",
    },
    {
        "scenario_id": "SC-3.2",
        "scenario_family": "budget_constraint",
        "scenario_name": "Budget Allocation Comparison (3-way)",
        "direction": "comparison",
        "target_scope": "ALL",
        "target_functions": "Claims,Technology,Finance,People",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "",
        "adoption_phases": "adoption,expansion",
        "alpha_adopt": 0.6, "alpha_expand": 0.3, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "moderate_reduction",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 40,
        "budget_total": 2000000,
        "max_risk_level": "medium",
        "time_horizon_months": 36,
        "objective": "compare_allocations",
        "events": "[]",
        "budget_allocations_json": '[{"name":"Tech-heavy","tech":2000000,"reskill":0,"change":0},{"name":"Balanced","tech":1000000,"reskill":500000,"change":500000},{"name":"People-heavy","tech":500000,"reskill":750000,"change":750000}]',
        "notes": "3-way comparison: tech-heavy vs balanced vs people-heavy investment",
    },
    {
        "scenario_id": "SC-5.3",
        "scenario_family": "output_target",
        "scenario_name": "+20% Output, -15% HC in Claims",
        "direction": "inverse",
        "target_scope": "Claims",
        "target_functions": "Claims",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "",
        "adoption_phases": "adoption,expansion,extension",
        "alpha_adopt": 0.7, "alpha_expand": 0.4, "alpha_extend": 0.2,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "active_reduction",
        "redistribution_mode": "automate_first",
        "readiness_threshold": 60,
        "budget_total": 4000000,
        "max_risk_level": "high",
        "time_horizon_months": 24,
        "objective": "achieve_dual_target",
        "events": "[]",
        "target_metric": "dual",
        "target_output_change_pct": 20,
        "target_hc_change_pct": -15,
        "notes": "Hardest scenario — more output with fewer people. Feasibility test.",
    },
    {
        "scenario_id": "SC-12.2",
        "scenario_family": "composite",
        "scenario_name": "$15M in 24 Months (What Does It Take?)",
        "direction": "inverse",
        "target_scope": "ALL",
        "target_functions": "Claims,Technology,Finance,People",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "",
        "adoption_phases": "adoption,expansion,extension",
        "alpha_adopt": 0.8, "alpha_expand": 0.5, "alpha_extend": 0.3,
        "s_curve_k": 0.35, "s_curve_midpoint": 3,
        "hc_policy": "active_reduction",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 55,
        "budget_total": 0,
        "max_risk_level": "medium",
        "time_horizon_months": 24,
        "objective": "find_minimum_program",
        "events": "[]",
        "target_metric": "net_savings",
        "target_value": 15000000,
        "min_quality": 0.90,
        "notes": "Meta-inverse: what minimum program achieves $15M savings in 24 months?",
    },
    {
        "scenario_id": "SC-4.3",
        "scenario_family": "automation_target",
        "scenario_name": "Task Category Targets",
        "direction": "inverse",
        "target_scope": "ALL",
        "target_functions": "Claims,Technology,Finance,People",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "",
        "adoption_phases": "adoption,expansion,extension",
        "alpha_adopt": 0.7, "alpha_expand": 0.4, "alpha_extend": 0.2,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "moderate_reduction",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 50,
        "budget_total": 6000000,
        "max_risk_level": "high",
        "time_horizon_months": 36,
        "objective": "achieve_category_targets",
        "events": "[]",
        "target_metric": "automation_by_category",
        "category_targets_json": '{"directive":90,"feedback_loop":80,"task_iteration":50,"learning":30,"validation":40,"negligibility":0}',
        "notes": "Category-level automation targets — reveals future shape of work",
    },

    # -------------------------------------------------------
    # PRIORITY 3: Comparison & Sequencing (8)
    # -------------------------------------------------------
    {
        "scenario_id": "SC-9.1a",
        "scenario_family": "sequencing",
        "scenario_name": "Sequence: Claims → Finance → People",
        "direction": "forward",
        "target_scope": "ALL",
        "target_functions": "Claims,Finance,People",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "1,13,25",
        "adoption_phases": "adoption,expansion",
        "alpha_adopt": 0.6, "alpha_expand": 0.3, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "moderate_reduction",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 45,
        "budget_total": 5000000,
        "max_risk_level": "medium",
        "time_horizon_months": 36,
        "objective": "maximize_savings",
        "events": "[]",
        "compare_with": "SC-9.1b,SC-9.1c",
        "notes": "Path A: Claims first (highest potential, lowest readiness)",
    },
    {
        "scenario_id": "SC-9.1b",
        "scenario_family": "sequencing",
        "scenario_name": "Sequence: People → Finance → Claims",
        "direction": "forward",
        "target_scope": "ALL",
        "target_functions": "People,Finance,Claims",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "1,13,25",
        "adoption_phases": "adoption,expansion",
        "alpha_adopt": 0.6, "alpha_expand": 0.3, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "moderate_reduction",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 45,
        "budget_total": 5000000,
        "max_risk_level": "medium",
        "time_horizon_months": 36,
        "objective": "maximize_savings",
        "events": "[]",
        "compare_with": "SC-9.1a,SC-9.1c",
        "notes": "Path B: People first (easiest, builds capital)",
    },
    {
        "scenario_id": "SC-9.1c",
        "scenario_family": "sequencing",
        "scenario_name": "Sequence: Finance → Claims → People",
        "direction": "forward",
        "target_scope": "ALL",
        "target_functions": "Finance,Claims,People",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "1,13,25",
        "adoption_phases": "adoption,expansion",
        "alpha_adopt": 0.6, "alpha_expand": 0.3, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "moderate_reduction",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 45,
        "budget_total": 5000000,
        "max_risk_level": "medium",
        "time_horizon_months": 36,
        "objective": "maximize_savings",
        "events": "[]",
        "compare_with": "SC-9.1a,SC-9.1b",
        "notes": "Path C: Finance first (moderate potential, moderate readiness)",
    },
    {
        "scenario_id": "SC-9.3a",
        "scenario_family": "sequencing",
        "scenario_name": "Phase: Reskill → Deploy → Reduce",
        "direction": "forward",
        "target_scope": "Claims",
        "target_functions": "Claims",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "7",
        "adoption_phases": "adoption,expansion",
        "alpha_adopt": 0.6, "alpha_expand": 0.3, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "moderate_reduction",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 45,
        "budget_total": 3000000,
        "max_risk_level": "medium",
        "time_horizon_months": 36,
        "objective": "maximize_savings",
        "events": "[]",
        "reskilling_start_month": 1,
        "deployment_start_month": 7,
        "reduction_start_month": 13,
        "compare_with": "SC-9.3b,SC-9.3c",
        "notes": "People first: reskill months 1-6, deploy month 7, reduce month 13",
    },
    {
        "scenario_id": "SC-9.3b",
        "scenario_family": "sequencing",
        "scenario_name": "Phase: Deploy → Reskill → Reduce",
        "direction": "forward",
        "target_scope": "Claims",
        "target_functions": "Claims",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "1",
        "adoption_phases": "adoption,expansion",
        "alpha_adopt": 0.6, "alpha_expand": 0.3, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "moderate_reduction",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 0,
        "budget_total": 3000000,
        "max_risk_level": "medium",
        "time_horizon_months": 36,
        "objective": "maximize_savings",
        "events": "[]",
        "reskilling_start_month": 4,
        "deployment_start_month": 1,
        "reduction_start_month": 10,
        "compare_with": "SC-9.3a,SC-9.3c",
        "notes": "Tech first: deploy month 1, reskill month 4, reduce month 10",
    },
    {
        "scenario_id": "SC-9.3c",
        "scenario_family": "sequencing",
        "scenario_name": "Phase: Deploy → Reduce → Reskill",
        "direction": "forward",
        "target_scope": "Claims",
        "target_functions": "Claims",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "1",
        "adoption_phases": "adoption",
        "alpha_adopt": 0.6, "alpha_expand": 0.0, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "active_reduction",
        "redistribution_mode": "absorb_adjacent",
        "readiness_threshold": 0,
        "budget_total": 2000000,
        "max_risk_level": "high",
        "time_horizon_months": 36,
        "objective": "maximize_savings",
        "events": "[]",
        "reskilling_start_month": 10,
        "deployment_start_month": 1,
        "reduction_start_month": 4,
        "compare_with": "SC-9.3a,SC-9.3b",
        "notes": "Cut first (WARNING): deploy month 1, reduce month 4, reskill month 10 — expected to fail",
    },
    {
        "scenario_id": "SC-7.2",
        "scenario_family": "function_transformation",
        "scenario_name": "Which Function First? (3-way comparison)",
        "direction": "comparison",
        "target_scope": "SINGLE_FUNCTION",
        "target_functions": "Claims,Finance,People",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "1",
        "adoption_phases": "adoption,expansion",
        "alpha_adopt": 0.6, "alpha_expand": 0.3, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "moderate_reduction",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 0,
        "budget_total": 2000000,
        "max_risk_level": "medium",
        "time_horizon_months": 18,
        "objective": "compare_functions",
        "events": "[]",
        "notes": "Same budget and policy applied to each function independently — which generates best ROI and political capital?",
    },
    {
        "scenario_id": "SC-8.2",
        "scenario_family": "skill_intervention",
        "scenario_name": "Reskill vs. Hire vs. Contract (AI Ops)",
        "direction": "comparison",
        "target_scope": "ALL",
        "target_functions": "Claims,Technology",
        "target_roles": "",
        "tools": "",
        "deployment_months": "",
        "adoption_phases": "",
        "alpha_adopt": 0.0, "alpha_expand": 0.0, "alpha_extend": 0.0,
        "s_curve_k": 0.0, "s_curve_midpoint": 0,
        "hc_policy": "no_change",
        "redistribution_mode": "none",
        "readiness_threshold": 0,
        "budget_total": 1000000,
        "max_risk_level": "low",
        "time_horizon_months": 24,
        "objective": "compare_skill_options",
        "events": "[]",
        "skill_need": "AI Operations",
        "quantity_needed": 30,
        "options_json": '[{"method":"reskill","source":"CL-003","duration_mo":8,"cost_pp":8000,"success_rate":0.75},{"method":"hire","time_to_fill_mo":4,"cost_pp":15000,"salary_premium":12000},{"method":"contract","hourly_rate":85,"ramp_mo":1}]',
        "notes": "Build vs buy vs borrow — cost, time, cultural impact comparison",
    },

    # -------------------------------------------------------
    # PRIORITY 4: Sensitivity & Stress Tests (8)
    # -------------------------------------------------------
    {
        "scenario_id": "SC-10.1",
        "scenario_family": "sensitivity",
        "scenario_name": "Readiness Sweep (20→90)",
        "direction": "sensitivity",
        "target_scope": "Claims",
        "target_functions": "Claims",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "1",
        "adoption_phases": "adoption,expansion",
        "alpha_adopt": 0.6, "alpha_expand": 0.3, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "moderate_reduction",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 0,
        "budget_total": 3000000,
        "max_risk_level": "high",
        "time_horizon_months": 36,
        "objective": "sensitivity_analysis",
        "events": "[]",
        "sweep_parameter": "change_readiness",
        "sweep_range": "[20,30,40,50,60,70,80,90]",
        "notes": "Most critical parameter — expect breakpoint at ~40",
    },
    {
        "scenario_id": "SC-10.2",
        "scenario_family": "sensitivity",
        "scenario_name": "Readiness × Proficiency Interaction",
        "direction": "sensitivity",
        "target_scope": "Claims",
        "target_functions": "Claims",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "1",
        "adoption_phases": "adoption,expansion",
        "alpha_adopt": 0.6, "alpha_expand": 0.3, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "moderate_reduction",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 0,
        "budget_total": 3000000,
        "max_risk_level": "high",
        "time_horizon_months": 36,
        "objective": "sensitivity_analysis",
        "events": "[]",
        "sweep_parameter": "change_readiness,ai_proficiency",
        "sweep_range": '{"change_readiness":[30,50,70],"ai_proficiency":[20,40,60]}',
        "notes": "3×3 interaction matrix — proves multiplicative effect",
    },
    {
        "scenario_id": "SC-10.3",
        "scenario_family": "stress_test",
        "scenario_name": "Trust Destruction (2 AI Errors)",
        "direction": "forward",
        "target_scope": "Claims",
        "target_functions": "Claims",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "1",
        "adoption_phases": "adoption,expansion",
        "alpha_adopt": 0.6, "alpha_expand": 0.3, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "moderate_reduction",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 0,
        "budget_total": 3000000,
        "max_risk_level": "medium",
        "time_horizon_months": 36,
        "objective": "stress_test",
        "events": '[{"month":6,"type":"ai_error","severity":"high","function":"Claims"},{"month":10,"type":"ai_error","severity":"medium","function":"Claims"}]',
        "notes": "Two AI errors — proves trust asymmetry and recovery dynamics",
    },
    {
        "scenario_id": "SC-10.4",
        "scenario_family": "stress_test",
        "scenario_name": "Attrition Shock (15% Tech Loss)",
        "direction": "forward",
        "target_scope": "Technology",
        "target_functions": "Technology",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "1",
        "adoption_phases": "adoption,expansion",
        "alpha_adopt": 0.6, "alpha_expand": 0.3, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "moderate_reduction",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 0,
        "budget_total": 3000000,
        "max_risk_level": "high",
        "time_horizon_months": 36,
        "objective": "stress_test",
        "events": '[{"month":8,"type":"attrition_spike","function":"Technology","magnitude_pct":15}]',
        "notes": "Sudden talent loss — proves cascading impact on in-flight programs",
    },
    {
        "scenario_id": "SC-10.5",
        "scenario_family": "stress_test",
        "scenario_name": "Breakpoint: HC Reduction Limit",
        "direction": "sensitivity",
        "target_scope": "Claims",
        "target_functions": "Claims",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "1",
        "adoption_phases": "adoption,expansion,extension",
        "alpha_adopt": 0.8, "alpha_expand": 0.5, "alpha_extend": 0.3,
        "s_curve_k": 0.35, "s_curve_midpoint": 3,
        "hc_policy": "active_reduction",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 0,
        "budget_total": 5000000,
        "max_risk_level": "critical",
        "time_horizon_months": 36,
        "objective": "find_breakpoint",
        "events": "[]",
        "sweep_parameter": "target_headcount_reduction_pct",
        "sweep_range": "[5,10,15,20,25,30,35,40,45,50]",
        "quality_threshold": 0.85,
        "notes": "Find the HC reduction % where quality collapses (B1 vicious cycle triggers)",
    },
    {
        "scenario_id": "SC-11.1",
        "scenario_family": "regulatory",
        "scenario_name": "New Compliance Requirements (+30 tasks)",
        "direction": "forward",
        "target_scope": "Claims",
        "target_functions": "Claims",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "1",
        "adoption_phases": "adoption,expansion",
        "alpha_adopt": 0.6, "alpha_expand": 0.3, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "moderate_reduction",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 45,
        "budget_total": 3000000,
        "max_risk_level": "medium",
        "time_horizon_months": 36,
        "objective": "regulatory_impact",
        "events": '[{"month":1,"type":"regulation_change","additional_mandated_human_tasks":30,"function":"Claims"}]',
        "notes": "30 more tasks become compliance-mandated human — ceiling compresses",
    },
    {
        "scenario_id": "SC-11.2",
        "scenario_family": "regulatory",
        "scenario_name": "AI Now Permitted for Claims Triage",
        "direction": "forward",
        "target_scope": "Claims",
        "target_functions": "Claims",
        "target_roles": "",
        "tools": "Custom Claims AI",
        "deployment_months": "1",
        "adoption_phases": "adoption,expansion",
        "alpha_adopt": 0.6, "alpha_expand": 0.3, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "moderate_reduction",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 45,
        "budget_total": 3000000,
        "max_risk_level": "medium",
        "time_horizon_months": 36,
        "objective": "regulatory_impact",
        "events": '[{"month":1,"type":"regulation_relaxation","unlocked_tasks":["claims_triage","initial_review"],"function":"Claims"}]',
        "notes": "Regulation relaxation unlocks previously forbidden automation — ceiling expands",
    },
    {
        "scenario_id": "SC-12.4",
        "scenario_family": "competitive",
        "scenario_name": "Competitor Match: 50% Claims Automation",
        "direction": "inverse",
        "target_scope": "Claims",
        "target_functions": "Claims",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "",
        "adoption_phases": "adoption,expansion,extension",
        "alpha_adopt": 0.8, "alpha_expand": 0.5, "alpha_extend": 0.3,
        "s_curve_k": 0.4, "s_curve_midpoint": 3,
        "hc_policy": "rapid_redeployment",
        "redistribution_mode": "automate_first",
        "readiness_threshold": 60,
        "budget_total": 0,
        "max_risk_level": "high",
        "time_horizon_months": 18,
        "objective": "match_competitor",
        "events": "[]",
        "target_metric": "automation_pct",
        "target_value": 50,
        "urgency": "high",
        "notes": "Compressed timeline — what does it take to match competitor in 18 months?",
    },

    # -------------------------------------------------------
    # PRIORITY 5: Composite & Advanced (8)
    # -------------------------------------------------------
    {
        "scenario_id": "SC-12.1",
        "scenario_family": "composite",
        "scenario_name": "Full 36-Month Transformation Program",
        "direction": "forward",
        "target_scope": "ALL",
        "target_functions": "Claims,Technology,Finance,People",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "",
        "adoption_phases": "adoption,expansion,extension",
        "alpha_adopt": 0.7, "alpha_expand": 0.4, "alpha_extend": 0.2,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "moderate_reduction",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 45,
        "budget_total": 8000000,
        "max_risk_level": "high",
        "time_horizon_months": 36,
        "objective": "maximize_savings",
        "events": "[]",
        "workstreams_json": '[{"name":"Claims Quick Wins","start":1,"end":6,"type":"adoption_gap","scope":"Claims"},{"name":"Org-wide Copilot","start":3,"end":12,"tool":"Copilot","scope":"ALL"},{"name":"Claims AI Deep","start":7,"end":18,"tool":"Custom Claims AI","scope":"Claims"},{"name":"Finance Automation","start":10,"end":24,"scope":"Finance"},{"name":"People Simplification","start":13,"end":24,"scope":"People"},{"name":"Reskilling Wave 1","start":1,"end":12,"type":"reskill","scope":"Claims,Finance"},{"name":"Reskilling Wave 2","start":13,"end":24,"type":"reskill","scope":"People,Technology"},{"name":"Org Restructure","start":19,"end":30,"type":"restructure","scope":"ALL"}]',
        "notes": "Full complexity — 8 concurrent workstreams interacting through shared human system",
    },
    {
        "scenario_id": "SC-12.3",
        "scenario_family": "composite",
        "scenario_name": "3-Year with Moving Ceiling (Annual Reassessment)",
        "direction": "forward",
        "target_scope": "ALL",
        "target_functions": "Claims,Technology,Finance,People",
        "target_roles": "",
        "tools": "ALL_AVAILABLE",
        "deployment_months": "1",
        "adoption_phases": "adoption,expansion,extension",
        "alpha_adopt": 0.6, "alpha_expand": 0.3, "alpha_extend": 0.2,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "moderate_reduction",
        "redistribution_mode": "hybrid",
        "readiness_threshold": 45,
        "budget_total": 6000000,
        "max_risk_level": "medium",
        "time_horizon_months": 36,
        "objective": "maximize_savings",
        "events": '[{"month":12,"type":"etter_refresh","ceiling_increase_pct":8},{"month":24,"type":"etter_refresh","ceiling_increase_pct":8}]',
        "notes": "Rising ceiling — each annual reassessment reopens adoption gap (free money again)",
    },
    {
        "scenario_id": "SC-7.3",
        "scenario_family": "function_transformation",
        "scenario_name": "Claims-to-Payment Workflow Automation",
        "direction": "forward",
        "target_scope": "WORKFLOW",
        "target_functions": "Claims,Finance",
        "target_roles": "CL-001,CL-002,CL-005,FI-001,FI-002",
        "tools": "Custom Claims AI,UiPath RPA",
        "deployment_months": "1,1",
        "adoption_phases": "adoption,expansion",
        "alpha_adopt": 0.7, "alpha_expand": 0.4, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "moderate_reduction",
        "redistribution_mode": "automate_first",
        "readiness_threshold": 50,
        "budget_total": 3000000,
        "max_risk_level": "medium",
        "time_horizon_months": 24,
        "objective": "workflow_optimization",
        "events": "[]",
        "workflow_handoffs_eliminated": 5,
        "workflow_nonlinear_bonus_pct": 15,
        "notes": "Cross-function workflow automation — impact > sum of task automation",
    },
    {
        "scenario_id": "SC-7.4",
        "scenario_family": "org_restructure",
        "scenario_name": "Merge Claims Processing + Review",
        "direction": "forward",
        "target_scope": "Claims",
        "target_functions": "Claims",
        "target_roles": "",
        "tools": "",
        "deployment_months": "",
        "adoption_phases": "",
        "alpha_adopt": 0.0, "alpha_expand": 0.0, "alpha_extend": 0.0,
        "s_curve_k": 0.0, "s_curve_midpoint": 0,
        "hc_policy": "level_consolidation",
        "redistribution_mode": "absorb_adjacent",
        "readiness_threshold": 50,
        "budget_total": 500000,
        "max_risk_level": "medium",
        "time_horizon_months": 18,
        "objective": "structural_optimization",
        "events": "[]",
        "merge_sub_functions": "Claims Processing,Claims Review",
        "notes": "Structural change — combined headcount, eliminated management overlap",
    },
    {
        "scenario_id": "SC-6.2",
        "scenario_family": "role_transformation",
        "scenario_name": "Eliminate Claims Data Entry Clerk",
        "direction": "forward",
        "target_scope": "CL-003",
        "target_functions": "Claims",
        "target_roles": "CL-003",
        "tools": "UiPath RPA,Custom Claims AI",
        "deployment_months": "1,1",
        "adoption_phases": "adoption",
        "alpha_adopt": 0.8, "alpha_expand": 0.0, "alpha_extend": 0.0,
        "s_curve_k": 0.35, "s_curve_midpoint": 3,
        "hc_policy": "role_elimination",
        "redistribution_mode": "automate_first",
        "readiness_threshold": 45,
        "budget_total": 500000,
        "max_risk_level": "medium",
        "time_horizon_months": 12,
        "objective": "role_elimination",
        "events": "[]",
        "notes": "Full role removal (80 people, $3M savings) — cascade to adjacent roles",
    },
    {
        "scenario_id": "SC-6.3",
        "scenario_family": "role_transformation",
        "scenario_name": "Create AI Operations Specialist Role",
        "direction": "forward",
        "target_scope": "ALL",
        "target_functions": "Claims,Technology",
        "target_roles": "",
        "tools": "",
        "deployment_months": "",
        "adoption_phases": "",
        "alpha_adopt": 0.0, "alpha_expand": 0.0, "alpha_extend": 0.0,
        "s_curve_k": 0.0, "s_curve_midpoint": 0,
        "hc_policy": "role_creation",
        "redistribution_mode": "migrate_tasks",
        "readiness_threshold": 0,
        "budget_total": 300000,
        "max_risk_level": "low",
        "time_horizon_months": 12,
        "objective": "role_creation",
        "events": "[]",
        "new_role_name": "AI Operations Specialist",
        "task_sources": "validation tasks from Claims, monitoring tasks from Technology",
        "notes": "New role absorbing AI oversight tasks — FTE sizing from migrated hours",
    },
    {
        "scenario_id": "SC-6.4",
        "scenario_family": "role_transformation",
        "scenario_name": "Role Vacancy: Claims Examiner Attrition",
        "direction": "forward",
        "target_scope": "CL-004",
        "target_functions": "Claims",
        "target_roles": "CL-004",
        "tools": "",
        "deployment_months": "",
        "adoption_phases": "",
        "alpha_adopt": 0.0, "alpha_expand": 0.0, "alpha_extend": 0.0,
        "s_curve_k": 0.0, "s_curve_midpoint": 0,
        "hc_policy": "no_change",
        "redistribution_mode": "absorb_adjacent",
        "readiness_threshold": 0,
        "budget_total": 0,
        "max_risk_level": "critical",
        "time_horizon_months": 12,
        "objective": "impact_assessment",
        "events": '[{"month":1,"type":"role_vacancy","role_id":"CL-004","loss_pct":100}]',
        "notes": "What happens when nobody does this job? Orphaned tasks, homeless skills, role vacuum",
    },
    {
        "scenario_id": "SC-2.4",
        "scenario_family": "headcount_target",
        "scenario_name": "Flatten Management Layers",
        "direction": "forward",
        "target_scope": "ALL",
        "target_functions": "Claims,Technology,Finance,People",
        "target_roles": "",
        "tools": "Microsoft Copilot",
        "deployment_months": "1",
        "adoption_phases": "adoption",
        "alpha_adopt": 0.5, "alpha_expand": 0.0, "alpha_extend": 0.0,
        "s_curve_k": 0.3, "s_curve_midpoint": 4,
        "hc_policy": "level_consolidation",
        "redistribution_mode": "absorb_adjacent",
        "readiness_threshold": 50,
        "budget_total": 1000000,
        "max_risk_level": "medium",
        "time_horizon_months": 18,
        "objective": "structural_optimization",
        "events": "[]",
        "levels_to_merge": "Manager,Senior Manager",
        "notes": "Flatten org — merge management levels, expand spans of control",
    },
]


def main():
    """Write all 40 scenarios to extended CSV."""
    # Collect all unique keys
    all_keys = set()
    for s in SCENARIOS:
        all_keys.update(s.keys())
    
    # Define field order (common fields first, then extras)
    primary_fields = [
        "scenario_id", "scenario_family", "scenario_name", "direction",
        "target_scope", "target_functions", "target_roles",
        "tools", "deployment_months", "adoption_phases",
        "alpha_adopt", "alpha_expand", "alpha_extend",
        "s_curve_k", "s_curve_midpoint",
        "hc_policy", "redistribution_mode", "readiness_threshold",
        "budget_total", "max_risk_level",
        "time_horizon_months", "objective",
        "events", "notes",
    ]
    extra_fields = sorted(all_keys - set(primary_fields))
    fieldnames = primary_fields + extra_fields
    
    path = os.path.join(OUTPUT_DIR, "simulation_scenarios_extended.csv")
    with open(path, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction='ignore')
        writer.writeheader()
        for s in SCENARIOS:
            # Fill missing fields with empty string
            row = {k: s.get(k, "") for k in fieldnames}
            writer.writerow(row)
    
    print(f"Written {len(SCENARIOS)} scenarios to {path}")
    
    # Summary statistics
    families = {}
    directions = {}
    for s in SCENARIOS:
        fam = s["scenario_family"]
        d = s["direction"]
        families[fam] = families.get(fam, 0) + 1
        directions[d] = directions.get(d, 0) + 1
    
    print(f"\nScenario Families:")
    for fam, cnt in sorted(families.items(), key=lambda x: -x[1]):
        print(f"  {fam}: {cnt}")
    
    print(f"\nDirections:")
    for d, cnt in sorted(directions.items(), key=lambda x: -x[1]):
        print(f"  {d}: {cnt}")
    
    # Also write summary JSON
    summary = {
        "total_scenarios": len(SCENARIOS),
        "families": families,
        "directions": directions,
        "priority_breakdown": {
            "P1_core_forward": 8,
            "P2_inverse_optimization": 8,
            "P3_comparison_sequencing": 8,
            "P4_sensitivity_stress": 8,
            "P5_composite_advanced": 8,
        },
    }
    summary_path = os.path.join(OUTPUT_DIR, "scenario_summary.json")
    with open(summary_path, 'w') as f:
        json.dump(summary, f, indent=2)
    print(f"\nSummary written to {summary_path}")


if __name__ == "__main__":
    main()
