apiVersion: batch/v1
kind: Job
metadata:
  name: alembic-upgrade
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    job-type: alembic
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | nindent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | nindent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | nindent 8 }}
{{- end }}
      containers:
        - name: alembic
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["alembic"]
          args: ["upgrade", "head"]
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: ETTER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "etter-backend.fullname" . }}
                  key: ETTER_DB_PASSWORD
