"""col chnages

Revision ID: 007915adff33
Revises: c598f5bc578d
Create Date: 2025-07-03 11:26:15.458082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007915adff33'
down_revision: Union[str, None] = 'c598f5bc578d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etter_userworkflowshistory', sa.Column(
        'unread_flag', sa.Boolean(), nullable=False, server_default='true'), schema='etter')
    op.drop_column('etter_userworkflowshistory', 'is_new', schema='etter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etter_userworkflowshistory', sa.Column('is_new', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False), schema='etter')
    op.drop_column('etter_userworkflowshistory', 'unread_flag', schema='etter')
    # ### end Alembic commands ###
