"""Added unique together constraint

Revision ID: 15fab164eb19
Revises: 0d120cb47af1
Create Date: 2025-06-23 10:40:35.963707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15fab164eb19'
down_revision: Union[str, None] = '0d120cb47af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['etter.etter_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='etter'
    )
    op.drop_constraint(op.f('etter_users_email_key'), 'etter_users', schema='etter', type_='unique')
    op.drop_constraint(op.f('etter_users_username_key'), 'etter_users', schema='etter', type_='unique')
    op.create_unique_constraint(None, 'etter_users', ['email', 'username'], schema='etter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'etter_users', schema='etter', type_='unique')
    op.create_unique_constraint(op.f('etter_users_username_key'), 'etter_users', ['username'], schema='etter', postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('etter_users_email_key'), 'etter_users', ['email'], schema='etter', postgresql_nulls_not_distinct=False)
    op.drop_table('token_blacklist', schema='etter')
    # ### end Alembic commands ###
