"""workflow unique fix

Revision ID: 170e6a4eb1c7
Revises: 5e1ac5febe3e
Create Date: 2025-07-14 11:59:02.633827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '170e6a4eb1c7'
down_revision: Union[str, None] = '5e1ac5febe3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('etter_userworkflowshistory_request_id_workflow_id_user_id_u_key'), 'etter_userworkflowshistory', schema='etter', type_='unique')
    op.create_unique_constraint(None, 'etter_userworkflowshistory', ['request_id', 'workflow_id', 'user_id', 'user_query', 'version_id'], schema='etter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'etter_userworkflowshistory', schema='etter', type_='unique')
    op.create_unique_constraint(op.f('etter_userworkflowshistory_request_id_workflow_id_user_id_u_key'), 'etter_userworkflowshistory', ['request_id', 'workflow_id', 'user_id', 'user_query'], schema='etter', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
