"""info for workflow

Revision ID: 1fa1e70b299c
Revises: 3668791824e7
Create Date: 2025-09-02 01:56:01.001709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fa1e70b299c'
down_revision: Union[str, None] = '3668791824e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etter_userworkflowshistory', sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='etter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etter_userworkflowshistory', 'info', schema='etter')
    # ### end Alembic commands ###
