"""workflow builder

Revision ID: 2e1c05801092
Revises: f8dd3b13a8e1
Create Date: 2025-11-07 14:07:41.465182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e1c05801092'
down_revision: Union[str, None] = 'f8dd3b13a8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etter_functionworkflow', sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='etter')
    op.add_column('etter_functionworkflow', sa.Column('priority', sa.String(length=20), nullable=True), schema='etter')
    op.add_column('etter_functionworkflow', sa.Column('frequency', sa.String(length=30), nullable=True), schema='etter')
    op.add_column('etter_functionworkflow', sa.Column('objective', sa.Text(), nullable=True), schema='etter')
    op.alter_column('etter_workflowtask', 'score', new_column_name='impact_score', existing_type=sa.Float(), schema='etter')
    op.add_column('etter_workflowtask', sa.Column('automation_priority', sa.String(length=20), nullable=True), schema='etter')
    op.add_column('etter_workflowtask', sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='etter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etter_workflowtask', 'score_breakdown', schema='etter')
    op.drop_column('etter_workflowtask', 'automation_priority', schema='etter')
    op.alter_column('etter_workflowtask', 'impact_score', new_column_name='score', existing_type=sa.Float(), schema='etter')
    op.drop_column('etter_functionworkflow', 'objective', schema='etter')
    op.drop_column('etter_functionworkflow', 'frequency', schema='etter')
    op.drop_column('etter_functionworkflow', 'priority', schema='etter')
    op.drop_column('etter_functionworkflow', 'insights', schema='etter')
    # ### end Alembic commands ###
