"""auth chnages

Revision ID: 3668791824e7
Revises: 9b8be66a30cc
Create Date: 2025-08-27 21:55:29.483953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3668791824e7'
down_revision: Union[str, None] = '9b8be66a30cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('etter_users', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='etter')
    op.drop_constraint(op.f('etter_users_email_username_key'), 'etter_users', schema='etter', type_='unique')
    op.create_unique_constraint(None, 'etter_users', ['email'], schema='etter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'etter_users', schema='etter', type_='unique')
    op.create_unique_constraint(op.f('etter_users_email_username_key'), 'etter_users', ['email', 'username'], schema='etter')
    op.alter_column('etter_users', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='etter')
    # ### end Alembic commands ###
