"""workflow builder

Revision ID: 54c3687efd04
Revises: 9e9e90171fbb
Create Date: 2025-10-14 13:34:34.476990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54c3687efd04'
down_revision: Union[str, None] = '9e9e90171fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etter_function',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('function_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['iris1.iris1_mastercompany.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('function_name', 'company_id', name='uix_function_company'),
    schema='etter'
    )
    op.create_table('etter_functionworkflow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('researcher_id', sa.Integer(), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('approval_status', sa.String(length=200), nullable=True),
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['etter.etter_users.id'], ),
    sa.ForeignKeyConstraint(['function_id'], ['etter.etter_function.id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['etter.etter_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_name', 'function_id', name='uix_workflow_function'),
    schema='etter'
    )
    op.create_table('etter_workflowtask',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('roles', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['etter.etter_functionworkflow.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_name', 'workflow_id', name='uix_task_workflow'),
    schema='etter'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etter_workflowtask', schema='etter')
    op.drop_table('etter_functionworkflow', schema='etter')
    op.drop_table('etter_function', schema='etter')
    # ### end Alembic commands ###
