"""role taxonomy

Revision ID: 553a170a5e45
Revises: 9fa1a750f97c
Create Date: 2025-12-11 14:03:12.968762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '553a170a5e45'
down_revision: Union[str, None] = '9fa1a750f97c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etter_role_taxonomy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=250), server_default='', nullable=True),
    sa.Column('job_role', sa.String(length=250), server_default='', nullable=True),
    sa.Column('job_title', sa.String(length=250), server_default='', nullable=False),
    sa.Column('occupation', sa.String(length=250), server_default='', nullable=False),
    sa.Column('job_family', sa.String(length=250), server_default='', nullable=False),
    sa.Column('job_level', sa.String(length=250), server_default='', nullable=True),
    sa.Column('job_track', sa.String(length=250), server_default='', nullable=True),
    sa.Column('management_level', sa.String(length=250), nullable=True),
    sa.Column('pay_grade', sa.String(length=250), nullable=True),
    sa.Column('draup_role', sa.String(length=250), nullable=True),
    sa.Column('job_description', sa.Text(), server_default='', nullable=True),
    sa.Column('general_summary', sa.Text(), server_default='', nullable=True),
    sa.Column('duties_responsibilities', sa.Text(), server_default='', nullable=True),
    sa.Column('work_experience', sa.Text(), server_default='', nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('others', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['etter.etter_users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['iris1.iris1_mastercompany.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['etter.etter_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'job_title', 'job_family', 'occupation', name='uix_role_taxonomy_company_job_family_occupation'),
    schema='etter'
    )
    op.drop_table('etter_taxonomy', schema='etter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etter_taxonomy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('occupation', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('job_family', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('job_track', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('job_level', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('job_role', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('general_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duties_and_responsibilities', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('education_required', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('work_experience', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wage_or_salary', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('job_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('skills', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('other_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('draup_role', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('job_function', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('sub_function', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['iris1.iris1_mastercompany.id'], name=op.f('etter_taxonomy_company_id_fkey')),
    sa.ForeignKeyConstraint(['document_id'], ['etter.etter_extracted_document.id'], name=op.f('etter_taxonomy_document_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('etter_taxonomy_pkey')),
    sa.UniqueConstraint('company_id', 'job_title', 'document_id', name=op.f('uix_taxonomy_company_job_document'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='etter'
    )
    op.drop_table('etter_role_taxonomy', schema='etter')
    # ### end Alembic commands ###
