"""workflow unique fix

Revision ID: 5ac1ceba58d3
Revises: 170e6a4eb1c7
Create Date: 2025-07-14 16:30:42.701750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ac1ceba58d3'
down_revision: Union[str, None] = '170e6a4eb1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chro_dashboard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('job_role', sa.String(length=200), nullable=False),
    sa.Column('etter_impact_score_id', sa.Integer(), nullable=True),
    sa.Column('validated_ai_impact_score_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['etter_impact_score_id'], ['etter.etter_userworkflowshistory.id'], ),
    sa.ForeignKeyConstraint(['validated_ai_impact_score_id'], ['etter.etter_userworkflowshistory.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['etter.etter_workflowinfo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='etter'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chro_dashboard', schema='etter')
    # ### end Alembic commands ###
