"""simualtor user

Revision ID: 5d0bc95b8d52
Revises: a3d05f9f18a2
Create Date: 2025-09-06 00:49:36.915270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d0bc95b8d52'
down_revision: Union[str, None] = 'a3d05f9f18a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etter_financialsimulator', sa.Column('modified_by', sa.Integer(), nullable=True), schema='etter')
    op.create_foreign_key(None, 'etter_financialsimulator', 'etter_users', ['modified_by'], ['id'], source_schema='etter', referent_schema='etter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'etter_financialsimulator', schema='etter', type_='foreignkey')
    op.drop_column('etter_financialsimulator', 'modified_by', schema='etter')
    # ### end Alembic commands ###
