"""col chnages

Revision ID: 5e1ac5febe3e
Revises: 6397b97efaf8
Create Date: 2025-07-13 23:41:06.872106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e1ac5febe3e'
down_revision: Union[str, None] = '6397b97efaf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etter_userworkflowshistory', sa.Column('version_id', sa.Integer(), nullable=True), schema='etter')
    op.add_column('etter_userworkflowshistory', sa.Column('is_etter_generated', sa.Boolean(), nullable=False, server_default='false'), schema='etter')
    op.add_column('etter_userworkflowshistory', sa.Column('score', sa.Integer(), nullable=True), schema='etter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etter_userworkflowshistory', 'score', schema='etter')
    op.drop_column('etter_userworkflowshistory', 'is_etter_generated', schema='etter')
    op.drop_column('etter_userworkflowshistory', 'version_id', schema='etter')
    # ### end Alembic commands ###
