"""userLevel status

Revision ID: 6397b97efaf8
Revises: 007915adff33
Create Date: 2025-07-03 17:27:34.265646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6397b97efaf8'
down_revision: Union[str, None] = '007915adff33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etter_userworkflowhistorystatus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unread_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['etter.etter_userworkflowshistory.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['etter.etter_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('history_id', 'user_id'),
    schema='etter'
    )
    op.drop_column('etter_userworkflowshistory', 'unread_flag', schema='etter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etter_userworkflowshistory', sa.Column('unread_flag', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False), schema='etter')
    op.drop_table('etter_userworkflowhistorystatus', schema='etter')
    # ### end Alembic commands ###
