"""Theme column in user table

Revision ID: 691c15f384d1
Revises: 15fab164eb19
Create Date: 2025-06-24 11:13:41.340741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '691c15f384d1'
down_revision: Union[str, None] = '15fab164eb19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etter_users', sa.Column('theme_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='etter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etter_users', 'theme_config', schema='etter')
    # ### end Alembic commands ###
