"""Removed unique together in user step history

Revision ID: 87453673c6c0
Revises: d8f9a0455801
Create Date: 2025-07-01 17:26:10.872511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87453673c6c0'
down_revision: Union[str, None] = 'd8f9a0455801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('etter_userworkflowstephistory', 'workflow_step_info_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='etter')
    op.drop_constraint(op.f('uix_history_user_version_step_version_step'), 'etter_userworkflowstephistory', schema='etter', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uix_history_user_version_step_version_step'), 'etter_userworkflowstephistory', ['user_workflow_history_id', 'version_id', 'workflow_step_info_id'], schema='etter', postgresql_nulls_not_distinct=False)
    op.alter_column('etter_userworkflowstephistory', 'workflow_step_info_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='etter')
    # ### end Alembic commands ###
