"""column type change

Revision ID: 88be18d4e56c
Revises: 5ac1ceba58d3
Create Date: 2025-07-15 08:06:23.752470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88be18d4e56c'
down_revision: Union[str, None] = '5ac1ceba58d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('etter_userworkflowshistory', 'score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True,
               schema='etter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('etter_userworkflowshistory', 'score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               schema='etter')
    # ### end Alembic commands ###
