"""skills for tasks

Revision ID: 8a06297f3f1b
Revises: 2e1c05801092
Create Date: 2025-11-07 17:43:18.470061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a06297f3f1b'
down_revision: Union[str, None] = '2e1c05801092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etter_workflowtask', sa.Column('skills_required', sa.ARRAY(sa.String()), nullable=True), schema='etter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etter_workflowtask', 'skills_required', schema='etter')
    # ### end Alembic commands ###
