"""add_s3_document_tables

Revision ID: 8c5278b962e8
Revises: a026bb7246de
Create Date: 2025-10-09 11:32:21.289140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c5278b962e8'
down_revision: Union[str, None] = 'a026bb7246de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s3_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('bucket', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('mode', sa.Enum('SINGLE', 'MULTIPART', name='uploadmode'), nullable=False),
    sa.Column('upload_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'UPLOADED', 'READY', 'DELETED', 'QUARANTINE', 'ABORTED', name='documentstatus'), nullable=False),
    sa.Column('declared_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('observed_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('declared_content_type', sa.Text(), nullable=True),
    sa.Column('observed_content_type', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('legal_hold', sa.Boolean(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='etter'
    )
    op.create_index(op.f('ix_etter_s3_documents_tenant_id'), 's3_documents', ['tenant_id'], unique=False, schema='etter')
    op.create_index('ix_s3_documents_status', 's3_documents', ['status'], unique=False, schema='etter')
    op.create_index('ix_s3_documents_tenant_role_created', 's3_documents', ['tenant_id', 'role', 'created_at'], unique=False, schema='etter')
    op.create_table('s3_idempotency_keys',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key'),
    schema='etter'
    )
    op.create_index(op.f('ix_etter_s3_idempotency_keys_tenant_id'), 's3_idempotency_keys', ['tenant_id'], unique=False, schema='etter')
    op.create_index('ix_s3_idempotency_keys_expires_at', 's3_idempotency_keys', ['expires_at'], unique=False, schema='etter')
    op.create_table('s3_audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.UUID(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['etter.s3_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='etter'
    )
    op.create_index(op.f('ix_etter_s3_audit_events_tenant_id'), 's3_audit_events', ['tenant_id'], unique=False, schema='etter')
    op.create_index(op.f('ix_etter_s3_audit_events_time'), 's3_audit_events', ['time'], unique=False, schema='etter')
    op.create_index('ix_s3_audit_events_document_id', 's3_audit_events', ['document_id'], unique=False, schema='etter')
    op.create_index('ix_s3_audit_events_tenant_action', 's3_audit_events', ['tenant_id', 'action'], unique=False, schema='etter')
    op.create_table('s3_document_parts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('part_number', sa.Integer(), nullable=False),
    sa.Column('etag', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['etter.s3_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'part_number', name='uq_s3_document_part'),
    schema='etter'
    )
    op.create_index('ix_s3_document_parts_document_id', 's3_document_parts', ['document_id'], unique=False, schema='etter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_s3_document_parts_document_id', table_name='s3_document_parts', schema='etter')
    op.drop_table('s3_document_parts', schema='etter')
    op.drop_index('ix_s3_audit_events_tenant_action', table_name='s3_audit_events', schema='etter')
    op.drop_index('ix_s3_audit_events_document_id', table_name='s3_audit_events', schema='etter')
    op.drop_index(op.f('ix_etter_s3_audit_events_time'), table_name='s3_audit_events', schema='etter')
    op.drop_index(op.f('ix_etter_s3_audit_events_tenant_id'), table_name='s3_audit_events', schema='etter')
    op.drop_table('s3_audit_events', schema='etter')
    op.drop_index('ix_s3_idempotency_keys_expires_at', table_name='s3_idempotency_keys', schema='etter')
    op.drop_index(op.f('ix_etter_s3_idempotency_keys_tenant_id'), table_name='s3_idempotency_keys', schema='etter')
    op.drop_table('s3_idempotency_keys', schema='etter')
    op.drop_index('ix_s3_documents_tenant_role_created', table_name='s3_documents', schema='etter')
    op.drop_index('ix_s3_documents_status', table_name='s3_documents', schema='etter')
    op.drop_index(op.f('ix_etter_s3_documents_tenant_id'), table_name='s3_documents', schema='etter')
    op.drop_table('s3_documents', schema='etter')
    # ### end Alembic commands ###
