"""wb sample data

Revision ID: 8da8f857274e
Revises: fe5b969914ba
Create Date: 2026-01-21 15:28:52.498906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8da8f857274e'
down_revision: Union[str, None] = 'fe5b969914ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etter_workflowbuildersampledata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master_function_id', sa.Integer(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('modified_by', sa.String(length=255), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['iris1.iris1_mastercompany.id'], ),
    sa.ForeignKeyConstraint(['master_function_id'], ['etter.etter_masterfunction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_function_id', 'company_id', name='uix_workflow_builder_master_function_company'),
    schema='etter'
    )
    op.add_column('etter_functionworkflow', sa.Column('source', sa.String(length=250), server_default='User', nullable=False), schema='etter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etter_functionworkflow', 'source', schema='etter')
    op.drop_table('etter_workflowbuildersampledata', schema='etter')
    # ### end Alembic commands ###
