"""upload docs

Revision ID: 91ad08339ff6
Revises: f1a2b3c4d5e6
Create Date: 2025-12-10 14:13:17.222219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91ad08339ff6'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create new enum types (without schema qualification for compatibility)
    op.execute("CREATE TYPE extractionstatus AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')")
    op.execute("CREATE TYPE approvalstatus AS ENUM ('PENDING', 'APPROVED', 'REJECTED')")
    op.execute("CREATE TYPE extractionsessionstatus AS ENUM ('ACTIVE', 'COMPLETED', 'ARCHIVED')")
    op.execute("CREATE TYPE uploadmodev2 AS ENUM ('FILESYSTEM', 'ROLE_BASED')")
    
    # Add roles column
    op.add_column('etter_extracted_document', sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='etter')
    
    # Convert status column to new enum type
    op.execute("""
        ALTER TABLE etter.etter_extracted_document 
        ALTER COLUMN status TYPE extractionstatus 
        USING status::text::extractionstatus
    """)
    
    # Convert approval_status column to new enum type
    op.execute("""
        ALTER TABLE etter.etter_extracted_document 
        ALTER COLUMN approval_status TYPE approvalstatus 
        USING approval_status::text::approvalstatus
    """)
    op.alter_column('etter_extracted_document', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='etter')
    op.alter_column('etter_extracted_document', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               schema='etter')
    op.drop_index(op.f('ix_etter_extracted_document_approval_status'), table_name='etter_extracted_document', schema='etter')
    op.drop_index(op.f('ix_etter_extracted_document_document_id'), table_name='etter_extracted_document', schema='etter')
    op.drop_index(op.f('ix_etter_extracted_document_session_id'), table_name='etter_extracted_document', schema='etter')
    op.drop_index(op.f('ix_etter_extracted_document_status'), table_name='etter_extracted_document', schema='etter')
    op.drop_constraint(op.f('etter_extracted_document_approved_by_fkey'), 'etter_extracted_document', schema='etter', type_='foreignkey')
    op.drop_constraint(op.f('etter_extracted_document_session_id_fkey'), 'etter_extracted_document', schema='etter', type_='foreignkey')
    op.create_foreign_key(None, 'etter_extracted_document', 'etter_extraction_session', ['session_id'], ['id'], source_schema='etter', referent_schema='etter')
    op.drop_column('etter_extracted_document', 'approved_by', schema='etter')
    op.drop_column('etter_extracted_document', 'approved_at', schema='etter')
    op.add_column('etter_extraction_session', sa.Column('approver_id', sa.Integer(), nullable=True), schema='etter')
    op.add_column('etter_extraction_session', sa.Column('approved_at', sa.DateTime(), nullable=True), schema='etter')
    # Convert extraction_session status column to new enum type
    op.execute("""
        ALTER TABLE etter.etter_extraction_session 
        ALTER COLUMN status TYPE extractionsessionstatus 
        USING status::text::extractionsessionstatus
    """)
    op.alter_column('etter_extraction_session', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='etter')
    op.alter_column('etter_extraction_session', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               schema='etter')
    op.drop_index(op.f('ix_etter_extraction_session_status'), table_name='etter_extraction_session', schema='etter')
    op.drop_index(op.f('ix_etter_extraction_session_user_id'), table_name='etter_extraction_session', schema='etter')
    
    # Add foreign key constraints using NOT VALID to avoid validating existing data
    # This allows adding the constraint even if some existing rows have invalid references
    # New inserts/updates will still be validated
    op.execute("""
        ALTER TABLE etter.etter_extraction_session 
        ADD CONSTRAINT etter_extraction_session_approver_id_fkey 
        FOREIGN KEY (approver_id) 
        REFERENCES etter.etter_users(id) 
        NOT VALID
    """)
    
    op.execute("""
        ALTER TABLE etter.etter_extraction_session 
        ADD CONSTRAINT etter_extraction_session_user_id_fkey 
        FOREIGN KEY (user_id) 
        REFERENCES etter.etter_users(id) 
        NOT VALID
    """)
    
    # Optional: Clean up invalid data after adding constraint
    # Uncomment the following if you want to delete sessions with invalid user_ids
    # op.execute("""
    #     DELETE FROM etter.etter_extraction_session 
    #     WHERE user_id NOT IN (SELECT id FROM etter.etter_users)
    # """)
    
    # Optional: Clean up invalid approver_ids
    # op.execute("""
    #     UPDATE etter.etter_extraction_session 
    #     SET approver_id = NULL 
    #     WHERE approver_id IS NOT NULL 
    #     AND approver_id NOT IN (SELECT id FROM etter.etter_users)
    # """)
    op.drop_index(op.f('idx_company'), table_name='etter_task_autocomplete_cache', schema='etter')
    op.drop_index(op.f('idx_company_role'), table_name='etter_task_autocomplete_cache', schema='etter')
    op.drop_index(op.f('idx_task_name_prefix'), table_name='etter_task_autocomplete_cache', schema='etter', postgresql_using='gin')
    op.drop_index(op.f('idx_updated_at'), table_name='etter_task_autocomplete_cache', schema='etter')
    op.alter_column('s3_documents', 'role',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='etter')
    
    op.drop_index(op.f('ix_s3_documents_mode_folder'), table_name='s3_documents', schema='etter')
    op.execute("DROP INDEX IF EXISTS etter.uq_s3_filesystem_path")
    
    # Convert s3_documents upload_mode column to new enum type
    # First cast to text, then to the new enum type
    # Use explicit CAST to avoid type comparison issues
    op.execute("""
        ALTER TABLE etter.s3_documents 
        ALTER COLUMN upload_mode TYPE uploadmodev2 
        USING CAST(upload_mode::text AS uploadmodev2)
    """)
    
    # Drop old enum types (only if they exist and are not used elsewhere)
    # Note: We keep the old types for now in case of rollback, but they can be dropped manually if needed
    # op.execute("DROP TYPE IF EXISTS etter.extraction_status")
    # op.execute("DROP TYPE IF EXISTS etter.approval_status")
    # op.execute("DROP TYPE IF EXISTS etter.extraction_session_status")
    # op.execute("DROP TYPE IF EXISTS uploadmode_v2")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_s3_filesystem_path'), 's3_documents', ['tenant_id', 'folder_path', 'original_filename'], unique=True, schema='etter', postgresql_where="((upload_mode = 'FILESYSTEM'::uploadmode_v2) AND (status <> 'DELETED'::documentstatus))")
    op.create_index(op.f('ix_s3_documents_mode_folder'), 's3_documents', ['upload_mode', 'folder_path', 'tenant_id'], unique=False, schema='etter')
    # Convert s3_documents upload_mode column back to old enum type
    # First cast to text, then to the old enum type
    # Use explicit CAST to avoid type comparison issues
    op.execute("""
        ALTER TABLE etter.s3_documents 
        ALTER COLUMN upload_mode TYPE uploadmode_v2 
        USING CAST(upload_mode::text AS uploadmode_v2)
    """)
    op.alter_column('s3_documents', 'role',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='etter')
    op.create_index(op.f('idx_updated_at'), 'etter_task_autocomplete_cache', ['updated_at'], unique=False, schema='etter')
    op.create_index(op.f('idx_task_name_prefix'), 'etter_task_autocomplete_cache', ['task_name'], unique=False, schema='etter', postgresql_using='gin')
    op.create_index(op.f('idx_company_role'), 'etter_task_autocomplete_cache', ['company', 'role'], unique=False, schema='etter')
    op.create_index(op.f('idx_company'), 'etter_task_autocomplete_cache', ['company'], unique=False, schema='etter')
    op.drop_constraint('etter_extraction_session_user_id_fkey', 'etter_extraction_session', schema='etter', type_='foreignkey')
    op.drop_constraint('etter_extraction_session_approver_id_fkey', 'etter_extraction_session', schema='etter', type_='foreignkey')
    op.create_index(op.f('ix_etter_extraction_session_user_id'), 'etter_extraction_session', ['user_id'], unique=False, schema='etter')
    op.create_index(op.f('ix_etter_extraction_session_status'), 'etter_extraction_session', ['status'], unique=False, schema='etter')
    op.alter_column('etter_extraction_session', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               schema='etter')
    op.alter_column('etter_extraction_session', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='etter')
    # Convert extraction_session status column back to old enum type
    op.execute("""
        ALTER TABLE etter.etter_extraction_session 
        ALTER COLUMN status TYPE etter.extraction_session_status 
        USING status::text::etter.extraction_session_status
    """)
    op.drop_column('etter_extraction_session', 'approved_at', schema='etter')
    op.drop_column('etter_extraction_session', 'approver_id', schema='etter')
    op.add_column('etter_extracted_document', sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='etter')
    op.add_column('etter_extracted_document', sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True), schema='etter')
    op.drop_constraint(None, 'etter_extracted_document', schema='etter', type_='foreignkey')
    op.create_foreign_key(op.f('etter_extracted_document_session_id_fkey'), 'etter_extracted_document', 'etter_extraction_session', ['session_id'], ['id'], source_schema='etter', referent_schema='etter', ondelete='CASCADE')
    op.create_foreign_key(op.f('etter_extracted_document_approved_by_fkey'), 'etter_extracted_document', 'etter_users', ['approved_by'], ['id'], source_schema='etter', referent_schema='etter')
    op.create_index(op.f('ix_etter_extracted_document_status'), 'etter_extracted_document', ['status'], unique=False, schema='etter')
    op.create_index(op.f('ix_etter_extracted_document_session_id'), 'etter_extracted_document', ['session_id'], unique=False, schema='etter')
    op.create_index(op.f('ix_etter_extracted_document_document_id'), 'etter_extracted_document', ['document_id'], unique=False, schema='etter')
    op.create_index(op.f('ix_etter_extracted_document_approval_status'), 'etter_extracted_document', ['approval_status'], unique=False, schema='etter')
    op.alter_column('etter_extracted_document', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               schema='etter')
    op.alter_column('etter_extracted_document', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='etter')
    # Convert approval_status column back to old enum type
    op.execute("""
        ALTER TABLE etter.etter_extracted_document 
        ALTER COLUMN approval_status TYPE etter.approval_status 
        USING approval_status::text::etter.approval_status
    """)
    
    # Convert status column back to old enum type
    op.execute("""
        ALTER TABLE etter.etter_extracted_document 
        ALTER COLUMN status TYPE etter.extraction_status 
        USING status::text::etter.extraction_status
    """)
    op.drop_column('etter_extracted_document', 'roles', schema='etter')
    
    # Drop new enum types
    op.execute("DROP TYPE IF EXISTS extractionstatus")
    op.execute("DROP TYPE IF EXISTS approvalstatus")
    op.execute("DROP TYPE IF EXISTS extractionsessionstatus")
    op.execute("DROP TYPE IF EXISTS uploadmodev2")
    # ### end Alembic commands ###
