"""taxonomy

Revision ID: 9fa1a750f97c
Revises: 91ad08339ff6
Create Date: 2025-12-11 08:56:28.694099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fa1a750f97c'
down_revision: Union[str, None] = '91ad08339ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etter_taxonomy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=250), nullable=True),
    sa.Column('job_title', sa.String(length=250), nullable=False),
    sa.Column('occupation', sa.String(length=250), nullable=True),
    sa.Column('job_family', sa.String(length=250), nullable=True),
    sa.Column('job_track', sa.String(length=250), nullable=True),
    sa.Column('job_level', sa.String(length=250), nullable=True),
    sa.Column('job_role', sa.String(length=250), nullable=True),
    sa.Column('general_summary', sa.Text(), nullable=True),
    sa.Column('duties_and_responsibilities', sa.Text(), nullable=True),
    sa.Column('education_required', sa.Text(), nullable=True),
    sa.Column('work_experience', sa.Text(), nullable=True),
    sa.Column('wage_or_salary', sa.String(length=250), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('other_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('draup_role', sa.String(length=250), nullable=True),
    sa.Column('job_function', sa.String(length=250), nullable=True),
    sa.Column('sub_function', sa.String(length=250), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['iris1.iris1_mastercompany.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['etter.etter_extracted_document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'job_title', 'document_id', name='uix_taxonomy_company_job_document'),
    schema='etter'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etter_taxonomy', schema='etter')
    # ### end Alembic commands ###
