"""modeling_state

Revision ID: a026bb7246de
Revises: 5d0bc95b8d52
Create Date: 2025-09-22 01:15:33.602357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a026bb7246de'
down_revision: Union[str, None] = '5d0bc95b8d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    modeling_state_enum = sa.Enum('INITIAL', 'IN_REVIEW', 'FINAL', name='modelingstate', schema='etter')
    modeling_state_enum.create(op.get_bind())
    op.add_column('etter_userworkflowshistory', sa.Column('modeling_state', modeling_state_enum, nullable=False, server_default='INITIAL'), schema='etter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etter_userworkflowshistory', 'modeling_state', schema='etter')
    modeling_state_enum = sa.Enum('INITIAL', 'IN_REVIEW', 'FINAL', name='modelingstate', schema='etter')
    modeling_state_enum.drop(op.get_bind())
    # ### end Alembic commands ###
