"""simualtor

Revision ID: a3d05f9f18a2
Revises: 1fa1e70b299c
Create Date: 2025-09-05 22:11:47.877904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3d05f9f18a2'
down_revision: Union[str, None] = '1fa1e70b299c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etter_financialsimulator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('last_ran_on', sa.DateTime(), nullable=False),
    sa.Column('simulation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['iris1.iris1_mastercompany.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='etter'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etter_financialsimulator', schema='etter')
    # ### end Alembic commands ###
