"""task feasibility

Revision ID: ab228f2269cf
Revises: eb4e29f0e45a
Create Date: 2025-11-13 11:49:29.179982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab228f2269cf'
down_revision: Union[str, None] = 'eb4e29f0e45a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etter_taskfeasibility',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_query', sa.String(length=200), nullable=True),
    sa.Column('task_name', sa.Text(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('etter_score', sa.Float(), nullable=True),
    sa.Column('model_score', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('median', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['iris1.iris1_mastercompany.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_query', 'task_name', name='uix_task_feasibility_company_userquery_task'),
    schema='etter'
    )
    op.alter_column('etter_users', 'image',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True,
               schema='etter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('etter_users', 'image',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True,
               schema='etter')
    op.drop_table('etter_taskfeasibility', schema='etter')
    # ### end Alembic commands ###
