"""tasks posiitons

Revision ID: ae711c52f73f
Revises: 9ff2afe0de2e
Create Date: 2025-10-17 11:59:34.164309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae711c52f73f'
down_revision: Union[str, None] = '9ff2afe0de2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('etter_workflowtask', sa.Column('position', sa.Integer(), nullable=False, server_default='0'), schema='etter')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etter_workflowtask', 'position', schema='etter')
    # ### end Alembic commands ###
