"""adjacency

Revision ID: bccb5dff5c8e
Revises: ae711c52f73f
Create Date: 2025-10-25 01:40:21.599376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bccb5dff5c8e'
down_revision: Union[str, None] = 'ae711c52f73f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE modelingstate AS ENUM ('INITIAL', 'IN_REVIEW', 'FINAL')")
    
    op.create_table('etter_roleadjacency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('job_role', sa.String(length=200), nullable=False),
    sa.Column('adjacency_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['iris1.iris1_mastercompany.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'job_role', name='uix_company_job_role'),
    schema='etter'
    )
    
    op.drop_column('etter_userworkflowshistory', 'modeling_state', schema='etter')
    op.add_column('etter_userworkflowshistory',
                  sa.Column('modeling_state', sa.Enum('INITIAL', 'IN_REVIEW', 'FINAL', name='modelingstate'), nullable=False, server_default='INITIAL'),
                  schema='etter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etter_userworkflowshistory', 'modeling_state', schema='etter')
    op.add_column('etter_userworkflowshistory',
                  sa.Column('modeling_state', sa.String(), nullable=False, server_default='INITIAL'),
                  schema='etter')
    op.drop_table('etter_roleadjacency', schema='etter')
    op.execute("DROP TYPE modelingstate")
    # ### end Alembic commands ###
