"""chro deletion

Revision ID: c0daa41ee78b
Revises: 4032c657b281
Create Date: 2025-12-29 13:13:50.444680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0daa41ee78b'
down_revision: Union[str, None] = '4032c657b281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_chro_dashboard_workflow_id'), table_name='chro_dashboard', schema='etter')
    op.drop_table('chro_dashboard', schema='etter')
   


def downgrade() -> None:
    """Downgrade schema."""
    op.create_table('chro_dashboard',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_role', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('etter_impact_score_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('validated_ai_impact_score_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['etter_impact_score_id'], ['etter.etter_userworkflowshistory.id'], name=op.f('chro_dashboard_etter_impact_score_id_fkey')),
    sa.ForeignKeyConstraint(['validated_ai_impact_score_id'], ['etter.etter_userworkflowshistory.id'], name=op.f('chro_dashboard_validated_ai_impact_score_id_fkey')),
    sa.ForeignKeyConstraint(['workflow_id'], ['etter.etter_workflowinfo.id'], name=op.f('chro_dashboard_workflow_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chro_dashboard_pkey')),
    schema='etter'
    )
    op.create_index(op.f('idx_chro_dashboard_workflow_id'), 'chro_dashboard', ['workflow_id'], unique=False, schema='etter')
    # ### end Alembic commands ###
