"""col chnages

Revision ID: c598f5bc578d
Revises: 87453673c6c0
Create Date: 2025-07-03 10:41:38.590041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c598f5bc578d'
down_revision: Union[str, None] = '87453673c6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etter_userworkflowshistory',
                  sa.Column('is_new', sa.Boolean(), nullable=False, server_default='false'),
                  schema='etter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etter_userworkflowshistory', 'is_new', schema='etter')
    # ### end Alembic commands ###
