"""taxonomy source

Revision ID: d7253eaff019
Revises: 228d2632c843
Create Date: 2026-01-19 15:18:38.422275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7253eaff019'
down_revision: Union[str, None] = '228d2632c843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etter_role_taxonomy', sa.Column('source', sa.String(length=250), server_default='client_taxonomy', nullable=False), schema='etter')
    op.alter_column('etter_role_taxonomy', 'modified_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='etter')
    op.add_column('etter_skill_taxonomy', sa.Column('skill_type', sa.String(length=200), nullable=True), schema='etter')
    op.add_column('etter_skill_taxonomy', sa.Column('source', sa.String(length=250), server_default='client_taxonomy', nullable=False), schema='etter')
    op.alter_column('etter_skill_taxonomy', 'modified_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='etter')
    op.add_column('etter_tech_stack_taxonomy', sa.Column('source', sa.String(length=250), server_default='client_taxonomy', nullable=False), schema='etter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etter_tech_stack_taxonomy', 'source', schema='etter')
    op.alter_column('etter_skill_taxonomy', 'modified_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='etter')
    op.drop_column('etter_skill_taxonomy', 'source', schema='etter')
    op.drop_column('etter_skill_taxonomy', 'skill_type', schema='etter')
    op.alter_column('etter_role_taxonomy', 'modified_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='etter')
    op.drop_column('etter_role_taxonomy', 'source', schema='etter')
    # ### end Alembic commands ###
