"""History table migrations

Revision ID: d8f9a0455801
Revises: 691c15f384d1
Create Date: 2025-06-24 18:18:19.533408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8f9a0455801'
down_revision: Union[str, None] = '691c15f384d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etter_workflowinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_name', sa.String(length=200), nullable=False),
    sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('updated_by', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_name'),
    schema='etter'
    )
    op.create_table('etter_workflowstepsinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=200), nullable=False),
    sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('updated_by', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['etter.etter_workflowinfo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'step_name', name='uix_workflow_step'),
    schema='etter'
    )
    op.create_table('etter_userworkflowshistory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=200), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('user_query', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workflow_status', sa.String(length=200), nullable=False),
    sa.Column('approval_status', sa.String(length=200), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['etter.etter_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['etter.etter_users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['etter.etter_workflowinfo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'workflow_id', 'user_id', 'user_query'),
    schema='etter'
    )
    op.create_table('etter_userworkflowstephistory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=200), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('user_workflow_history_id', sa.Integer(), nullable=False),
    sa.Column('workflow_step_info_id', sa.Integer(), nullable=False),
    sa.Column('workflow_step_status', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review', sa.String(length=1000), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_workflow_history_id'], ['etter.etter_userworkflowshistory.id'], ),
    sa.ForeignKeyConstraint(['workflow_step_info_id'], ['etter.etter_workflowstepsinfo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_workflow_history_id', 'version_id', 'workflow_step_info_id', name='uix_history_user_version_step_version_step'),
    schema='etter'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etter_userworkflowstephistory', schema='etter')
    op.drop_table('etter_userworkflowshistory', schema='etter')
    op.drop_table('etter_workflowstepsinfo', schema='etter')
    op.drop_table('etter_workflowinfo', schema='etter')
    # ### end Alembic commands ###
