"""col changes

Revision ID: e78e7200800f
Revises: a026bb7246de
Create Date: 2025-10-08 17:21:35.939650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e78e7200800f'
down_revision: Union[str, None] = 'a026bb7246de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No-op migration - enum change removed as it's not necessary
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No-op migration - enum change removed as it's not necessary
    pass
    # ### end Alembic commands ###
