"""task columsn

Revision ID: eb4e29f0e45a
Revises: 8a06297f3f1b
Create Date: 2025-11-12 13:53:50.095047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb4e29f0e45a'
down_revision: Union[str, None] = '8a06297f3f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etter_workflowtask', sa.Column('sequence_number', sa.Integer(), nullable=True), schema='etter')
    op.add_column('etter_workflowtask', sa.Column('dependencies', sa.ARRAY(sa.Integer()), nullable=True), schema='etter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etter_workflowtask', 'dependencies', schema='etter')
    op.drop_column('etter_workflowtask', 'sequence_number', schema='etter')
    # ### end Alembic commands ###
