"""message

Revision ID: ebab3959204d
Revises: 8da8f857274e
Create Date: 2026-01-21 15:56:12.916001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebab3959204d'
down_revision: Union[str, None] = '8da8f857274e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etter_survey',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['iris1.iris1_mastercompany.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['etter.etter_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='etter'
    )
    op.create_table('etter_survey_response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feedback_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['etter.etter_survey.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['etter.etter_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('survey_id', 'user_id', name='uix_survey_user_response'),
    schema='etter'
    )
    op.create_table('etter_survey_skill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['etter.etter_skill_taxonomy.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['etter.etter_survey.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('survey_id', 'skill_id', name='uix_survey_skill'),
    schema='etter'
    )
    op.create_table('etter_survey_skill_response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_response_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['etter.etter_skill_taxonomy.id'], ),
    sa.ForeignKeyConstraint(['survey_response_id'], ['etter.etter_survey_response.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('survey_response_id', 'skill_id', name='uix_survey_response_skill'),
    schema='etter'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etter_survey_skill_response', schema='etter')
    op.drop_table('etter_survey_skill', schema='etter')
    op.drop_table('etter_survey_response', schema='etter')
    op.drop_table('etter_survey', schema='etter')
    # ### end Alembic commands ###
