"""remove version

Revision ID: f5c517c3d0b5
Revises: 88be18d4e56c
Create Date: 2025-07-15 13:39:17.962995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c517c3d0b5'
down_revision: Union[str, None] = '88be18d4e56c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('etter_userworkflowshistory_request_id_workflow_id_user_id_u_key'), 'etter_userworkflowshistory', schema='etter', type_='unique')
    op.create_unique_constraint(None, 'etter_userworkflowshistory', ['request_id', 'workflow_id', 'user_id', 'user_query'], schema='etter')
    op.drop_column('etter_userworkflowshistory', 'version_id', schema='etter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etter_userworkflowshistory', sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='etter')
    op.drop_constraint(None, 'etter_userworkflowshistory', schema='etter', type_='unique')
    op.create_unique_constraint(op.f('etter_userworkflowshistory_request_id_workflow_id_user_id_u_key'), 'etter_userworkflowshistory', ['request_id', 'workflow_id', 'user_id', 'user_query', 'version_id'], schema='etter', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
