"""sample data

Revision ID: f8dd3b13a8e1
Revises: bccb5dff5c8e
Create Date: 2025-11-04 12:18:56.159962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8dd3b13a8e1'
down_revision: Union[str, None] = 'bccb5dff5c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etter_sampledata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['iris1.iris1_mastercompany.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'role', 'company_id', name='uix_title_role_company'),
    schema='etter'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etter_sampledata', schema='etter')
    # ### end Alembic commands ###
