#!/bin/sh
set -e

# Generate runtime config from environment variables.
#
# API_BASE_URL     — workforce twin API (e.g. https://qa-etter.draup.technology/api/v1/workforce-twin)
# ETTER_API_BASE   — etter backend root for auth (e.g. https://qa-etter.draup.technology/api)
#
# If neither env var is set, config.js auto-detects environment from the browser hostname.
# Set these explicitly in Docker Compose / K8s to override auto-detection.

echo "=== Workforce Twin Frontend Startup ==="

# ── Determine serve directory (handle read-only /app in EKS) ──────
SERVE_DIR="/app"

# Build config.js content
if [ -n "$API_BASE_URL" ] || [ -n "$ETTER_API_BASE" ]; then
    echo "Environment variables detected — writing config.js overrides"
    echo "  API_BASE_URL   = ${API_BASE_URL:-(not set, will auto-detect)}"
    echo "  ETTER_API_BASE = ${ETTER_API_BASE:-(not set, will auto-detect)}"

    CONFIG_CONTENT="// Generated by docker-entrypoint.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
$([ -n "$API_BASE_URL" ] && echo "window.__WORKFORCE_TWIN_API_BASE__ = '${API_BASE_URL}';")
$([ -n "$ETTER_API_BASE" ] && echo "window.__ETTER_API_BASE__ = '${ETTER_API_BASE}';")
"
else
    echo "No API_BASE_URL or ETTER_API_BASE set"
    echo "Frontend will auto-detect environment from browser hostname (see config.js)"
    # Use default values so config.js is still written (needed for read-only fallback)
    CONFIG_CONTENT="window.__WORKFORCE_TWIN_API_BASE__ = '${API_BASE_URL:-/api}';
window.__ETTER_API_BASE__ = '${ETTER_API_BASE:-/etter-api}';
"
fi

# Write config.js — fall back to /tmp/app if /app is read-only (EKS)
if (echo "$CONFIG_CONTENT" > /app/config.js) 2>/dev/null; then
    SERVE_DIR="/app"
    echo "  config.js written to /app"
elif (mkdir -p /tmp/app && cp -r /app/. /tmp/app/ 2>/dev/null && echo "$CONFIG_CONTENT" > /tmp/app/config.js); then
    SERVE_DIR="/tmp/app"
    echo "INFO: /app read-only, serving from /tmp/app"
else
    echo "ERROR: could not write config.js" >&2
    exit 1
fi

# ── Find and start serve ─────────────────────────────────────────
SERVE_CMD=""
if [ -x /usr/local/bin/serve ]; then
    SERVE_CMD="/usr/local/bin/serve"
elif command -v serve >/dev/null 2>&1; then
    SERVE_CMD="serve"
else
    echo "ERROR: serve not found. Install with: npm install -g serve" >&2
    exit 1
fi

echo "=== Starting $SERVE_CMD -s $SERVE_DIR -l 3000 ==="
exec "$SERVE_CMD" -s "$SERVE_DIR" -l 3000
