#!/bin/sh
set -e

# Generate runtime config from environment variables.
#
# API_BASE_URL     — workforce twin API (e.g. https://qa-etter.draup.technology/api/v1/workforce-twin)
# ETTER_API_BASE   — etter backend root for auth (e.g. https://qa-etter.draup.technology/api)
#
# If neither env var is set, config.js auto-detects environment from the browser hostname.
# Set these explicitly in Docker Compose / K8s to override auto-detection.

echo "=== Workforce Twin Frontend Startup ==="

if [ -n "$API_BASE_URL" ] || [ -n "$ETTER_API_BASE" ]; then
    echo "Environment variables detected — writing config.js overrides"
    echo "  API_BASE_URL  = ${API_BASE_URL:-(not set, will auto-detect)}"
    echo "  ETTER_API_BASE = ${ETTER_API_BASE:-(not set, will auto-detect)}"

    # Only override globals that are explicitly set; leave others for auto-detection
    cat > /app/config.js <<ENVEOF
// Generated by docker-entrypoint.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
$([ -n "$API_BASE_URL" ] && echo "window.__WORKFORCE_TWIN_API_BASE__ = '${API_BASE_URL}';")
$([ -n "$ETTER_API_BASE" ] && echo "window.__ETTER_API_BASE__ = '${ETTER_API_BASE}';")
ENVEOF
else
    echo "No API_BASE_URL or ETTER_API_BASE set"
    echo "Frontend will auto-detect environment from browser hostname (see config.js)"
    # Don't overwrite config.js — the built-in auto-detection will handle it
fi

echo "=== Starting serve on port 3000 ==="
exec serve -s /app -l 3000
